openai_imagenet_template = [
    lambda c: f'a bad photo of a {c}.',
    lambda c: f'a photo of many {c}.',
    lambda c: f'a sculpture of a {c}.',
    lambda c: f'a photo of the hard to see {c}.',
    lambda c: f'a low resolution photo of the {c}.',
    lambda c: f'a rendering of a {c}.',
    lambda c: f'graffiti of a {c}.',
    lambda c: f'a bad photo of the {c}.',
    lambda c: f'a cropped photo of the {c}.',
    lambda c: f'a tattoo of a {c}.',
    lambda c: f'the embroidered {c}.',
    lambda c: f'a photo of a hard to see {c}.',
    lambda c: f'a bright photo of a {c}.',
    lambda c: f'a photo of a clean {c}.',
    lambda c: f'a photo of a dirty {c}.',
    lambda c: f'a dark photo of the {c}.',
    lambda c: f'a drawing of a {c}.',
    lambda c: f'a photo of my {c}.',
    lambda c: f'the plastic {c}.',
    lambda c: f'a photo of the cool {c}.',
    lambda c: f'a close-up photo of a {c}.',
    lambda c: f'a black and white photo of the {c}.',
    lambda c: f'a painting of the {c}.',
    lambda c: f'a painting of a {c}.',
    lambda c: f'a pixelated photo of the {c}.',
    lambda c: f'a sculpture of the {c}.',
    lambda c: f'a bright photo of the {c}.',
    lambda c: f'a cropped photo of a {c}.',
    lambda c: f'a plastic {c}.',
    lambda c: f'a photo of the dirty {c}.',
    lambda c: f'a jpeg corrupted photo of a {c}.',
    lambda c: f'a blurry photo of the {c}.',
    lambda c: f'a photo of the {c}.',
    lambda c: f'a good photo of the {c}.',
    lambda c: f'a rendering of the {c}.',
    lambda c: f'a {c} in a video game.',
    lambda c: f'a photo of one {c}.',
    lambda c: f'a doodle of a {c}.',
    lambda c: f'a close-up photo of the {c}.',
    lambda c: f'a photo of a {c}.',
    lambda c: f'the origami {c}.',
    lambda c: f'the {c} in a video game.',
    lambda c: f'a sketch of a {c}.',
    lambda c: f'a doodle of the {c}.',
    lambda c: f'a origami {c}.',
    lambda c: f'a low resolution photo of a {c}.',
    lambda c: f'the toy {c}.',
    lambda c: f'a rendition of the {c}.',
    lambda c: f'a photo of the clean {c}.',
    lambda c: f'a photo of a large {c}.',
    lambda c: f'a rendition of a {c}.',
    lambda c: f'a photo of a nice {c}.',
    lambda c: f'a photo of a weird {c}.',
    lambda c: f'a blurry photo of a {c}.',
    lambda c: f'a cartoon {c}.',
    lambda c: f'art of a {c}.',
    lambda c: f'a sketch of the {c}.',
    lambda c: f'a embroidered {c}.',
    lambda c: f'a pixelated photo of a {c}.',
    lambda c: f'itap of the {c}.',
    lambda c: f'a jpeg corrupted photo of the {c}.',
    lambda c: f'a good photo of a {c}.',
    lambda c: f'a plushie {c}.',
    lambda c: f'a photo of the nice {c}.',
    lambda c: f'a photo of the small {c}.',
    lambda c: f'a photo of the weird {c}.',
    lambda c: f'the cartoon {c}.',
    lambda c: f'art of the {c}.',
    lambda c: f'a drawing of the {c}.',
    lambda c: f'a photo of the large {c}.',
    lambda c: f'a black and white photo of a {c}.',
    lambda c: f'the plushie {c}.',
    lambda c: f'a dark photo of a {c}.',
    lambda c: f'itap of a {c}.',
    lambda c: f'graffiti of the {c}.',
    lambda c: f'a toy {c}.',
    lambda c: f'itap of my {c}.',
    lambda c: f'a photo of a cool {c}.',
    lambda c: f'a photo of a small {c}.',
    lambda c: f'a tattoo of the {c}.',
]


openai_imagenet_template_subset = {
    0: [
    lambda c: f'a photo of a {c}.',
    lambda c: f'a blurry photo of a {c}.',
    lambda c: f'a photo of many {c}.',
    lambda c: f'a photo of the large {c}.',
    lambda c: f'a photo of the small {c}.',
    ], 
    1: [
        lambda c: f'itap of my {c}.',
        lambda c: f'a bad photo of a {c}.',
        lambda c: f'a origami {c}.',
        lambda c: f'a photo of the large {c}.',
        lambda c: f'a {c} in a video game.',
        lambda c: f'art of the {c}.',
        lambda c: f'a photo of the small {c}.',
    ]
}
CUSTOM_TEMPLATES = {
    "pet37": lambda c: f"a photo of a {c}, a type of pet.",
    "OxfordFlowers": lambda c: f"a photo of a {c}, a type of flower.",
    "FGVCAircraft": lambda c: f"a photo of a {c}, a type of aircraft.",
    "DescribableTextures": lambda c: f"{c} texture.",
    "EuroSAT": lambda c: f"a centered satellite photo of {c}.",
    "StanfordCars": lambda c: f"a photo of a {c}, a type of car.",
    "food101": lambda c: f"a photo of {c}, a type of food.",
    "SUN397": lambda c: f"a photo of a {c}.",
    "Caltech101": lambda c: f"a photo of a {c}.",
    "UCF101": lambda c: f"a photo of a person doing {c}.",
    "ImageNet": lambda c: f"a photo of a {c}.",
    "ImageNetSketch": lambda c: f"a photo of a {c}.",
    "ImageNetV2": lambda c: f"a photo of a {c}.",
    "ImageNetA": lambda c: f"a photo of a {c}.",
    "ImageNetR": lambda c: f"a photo of a {c}.",
    "cub100_ID": lambda c: f"a photo of a {c},a type of bird.",
    "bird200": lambda c: f"a photo of a {c},a type of bird.",
    "food50_ID": lambda c: f"a photo of a {c},a type of food.",
    "pet18_ID": lambda c: f"a photo of the {c},a type of pet.",
    "car98_ID": lambda c: f"a photo of the {c},a type of car",
    "car196": lambda c: f"a photo of the {c},a type of car",
    "boat14_ID": lambda c: f"a photo of the {c},a type of boat.",
    "boat29": lambda c: f"a photo of the {c},a type of boat.",
}
CLASS_NAMES = {
    "OxfordPets": "pet.",
    "StanfordCars": "car",
    "Food101": "food",
    "cub100_ID": "bird.",
    "food50_ID": "food.",
    "pet18_ID": "pet.",
    "car98_ID": "car",
    "boat14_ID": "boat."
}
ADJUST_PARAMETER = {
    "cub100_ID": 0.9,
    "car98_ID": 0.9,
    "food50_ID": 0.9,
    "pet18_ID": 0.9,
    "boat14_ID": 0.5,
}